# Yvan: You need to update the repositories!

steps:
- id: docker-build-push-placeholders-run-bigquery
  waitFor: ['-']
  name: gcr.io/cloud-builders/docker
  entrypoint: bash
  args:
    - -c
    - |
      export IMAGE=${_REPO_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}
      docker build -t ${_REPO_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE} . &&
      docker push gcr.io/$PROJECT_ID/${_SERVICE}
      echo $IMAGE
      echo $IMAGE

- id: gcloud-run-deploy-placeholders-run-bigquery
  waitFor: ['docker-build-push-placeholders-run-bigquery']
  name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: bash
  args:
    - -c
    - |
      gcloud run deploy ${_SERVICE} \
        --project $PROJECT_ID \
        --image gcr.io/$PROJECT_ID/${_SERVICE} \
        --timeout 5m \
        --region ${_REGION} \
        --no-cpu-throttling \
        --min-instances 0 \
        --max-instances 5 \
        --allow-unauthenticated

substitutions:
  _SERVICE: placeholders-run-bigquery
  _REGION: us-central1
  _REPO_REGION: us
  _REPO: containers