FROM    node:20-bullseye AS builder
ENV     PROXY_HOST="127.0.0.1" \
        PROXY_PORT="9080" \
        PROJECT_ID="holy-diver-297719" \
        DATASET_ID="testing" \
        TABLE_ID="gsa_placeholder_testing" \
        HOST="0.0.0.0" \
        PORT="3000"
WORKDIR /app
COPY    package*.json .
RUN     npm i --silent
COPY    . .
RUN     npm run build
# Only necessary IF hosting directly in this container
CMD     ./startup

# FROM    nginx:latest
# COPY    --from=builder /app/dist /media/

